### ISSUE TITLE
Unable to SYNC test devices in Google Home companion app

### ISSUE THREAD

**Issue by xj13567180468** [actions-on-google/actionssdk-smart-home-nodejs#31] opened 2017-09-01 07:31 UTC
I have added a google action for a smart home app, actions.json is this:
{
  "actions": [{
    "name": "actions.devices",
    "fulfillment": {
      "conversationName": "automation"
    }
  }],
  "conversations": {
    "automation" :
    {
      "name": "automation",
      "url": "https://....../.../.../sync.do"
    }
  }
}
And Everything is ok after token exchange. When trying to add devices with my test application,
I do get the error message that the "Cloudn't update setting. Check your connection".I tried many times,
and My server never received the "action.devices.SYNC".my google account is ok.my phone also had reset any times. why? is actions.json can used any google accounts?

**Comment by AlexSneedMiller** [comment] 2017-09-01 15:03
@xj13567180468 I think you need to just copy the action.json from [here](https://github.com/actions-on-google/actionssdk-smart-home-nodejs/blob/master/action.json) and just replace the URL with the main API endpoint that handles the three different intents (SYNC, EXECUTE, QUERY)

**Comment by Fleker** [comment] 2017-09-01 17:07
This is a duplicate of issue #26. Please use that issue for issue triaging.

**Closed by Fleker** 2017-09-01 17:07 UTC
Labels: duplicate
