### ISSUE TITLE
action package issue

### ISSUE THREAD

**Issue by xj13567180468** [actions-on-google/actionssdk-smart-home-nodejs#33] opened 2017-09-04 02:08 UTC
I am registered four google devepoer accounts.then  I upload the same action package  for smart home.then everything is ok after token exchange. When trying to add devices with my test application.
I do get the error message that the "Cloudn't update setting. Check your connection".I tried many times.why? is the same action package only used one google account to smart home control?

**Comment by Fleker** [comment] 2017-09-04 08:34
Duplicate of #26 
Not an action package issue. It's something else. If you want, you can put your project id in #26, or [email it to me](mailto:fleker@google.com) along with your email that you used to use the project.

**Closed by Fleker** 2017-09-04 08:34 UTC
