### ISSUE TITLE
no welcome intent handle, is it normal?

### ISSUE THREAD

**Issue by xieyaxiong** [actions-on-google/actionssdk-smart-home-nodejs#20] opened 2017-07-21 03:21 UTC
`{
  "actions": [{
    "name": "actions.devices",
    "deviceControl": {
    },
    "fulfillment": {
      "conversationName": "automation"
    }
  }],
  "conversations": {
    "automation" :
    {
      "name": "automation",
      "url": "https://echo.goodk2.com:8000/GoogleHomeNew/konke.do"
    }
  }
}`

it's my action.json as same as official smart home document. no welcome intent in it. 
everything is ok in mobile app . but test in Simulator,  i say "talk to smart k " , it always response " Sorry, this action is not available in simulation" (debug info is empty)
is it normal?

**Comment by ekchatzi** [comment] 2017-07-24 19:30
I have the same issue

**Comment by Fleker** [comment] 2017-07-24 20:52
With smart home actions, there is no welcome intent. Instead, actions will simply be routed to your automation endpoint.

'Turn my lights on' or 'Set my lights to red' will simply execute the command on your device. You do not need to invoke an agent.

**Comment by ekchatzi** [comment] 2017-07-25 09:28
I have tried various phrases including the ones you suggested, with my phone, with the simulator and with an actual Google Home device, but I cannot get it to work. My "skill" is listed and I can add devices via the Home App, I can see the SYNC request and I respond just fine. The problem is when I try to test the EXECUTE and QUERY intents, I don't get anything on my endpoint. 

I am not a native English speaker (though I check that Google understands me with the history page) and I am located in Greece. I am also, like the original poster using a non-standard port (9005)

```javascript
{
	"actions": [{
		"name": "actions.devices",
		"deviceControl": {
		},
		"fulfillment": {
			"conversationName": "automation"
		}
	}],
	"conversations": {
		"automation" : {
			"name": "automation",
			"url": "https://internal.hamsystems.eu:9004/google-home-endpoint",
			"fulfillmentApiVersion": 2
		}
	}
}
```

Any help is greatly appreciated

**Comment by Fleker** [comment] 2017-07-25 18:17
When you handle the SYNC request, you should respond with a list of devices and the traits that each device can have. A lightbulb should have a type of `[action.devices.types.LIGHT](https://developers.google.com/actions/smarthome/light-schema)`. It should also have traits for what it can do, such as `action.devices.traits.OnOff` and `action.devices.traits.ColorSpectrum`. It should return enough data to the HomeGraph to make it possible to QUERY later. What are you returning with the SYNC?

**Comment by ekchatzi** [comment] 2017-07-26 10:48
Hello Nick, this is my respone to the SYNC:
```javascript
{
    "requestId": "10616006862255960353",
    "payload": {
        "agentUserId": 5,
        "devices": [
            {
                "id": "g:3",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Group"
                    ],
                    "name": "Park Lights"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Group",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "g:6",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Group"
                    ],
                    "name": "Suitcase"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Group",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "1:0",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM One"
                    ],
                    "name": "Plug"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM One",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "10:0",
                "type": "action.devices.types.THERMOSTAT",
                "traits": [
                    "action.devices.traits.TemperatureSetting"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Thermostat"
                    ],
                    "name": "Thermostat"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Thermostat",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "10:1",
                "type": "action.devices.types.THERMOSTAT",
                "traits": [
                    "action.devices.traits.TemperatureSetting"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Thermostat"
                    ],
                    "name": "Ham Thermostat"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Thermostat",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "10:2",
                "type": "action.devices.types.THERMOSTAT",
                "traits": [
                    "action.devices.traits.TemperatureSetting"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Thermostat"
                    ],
                    "name": "Thermostat"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Thermostat",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "11:1",
                "type": "action.devices.types.LIGHT",
                "traits": [
                    "action.devices.traits.OnOff",
                    "action.devices.traits.Brightness"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Triple Dimmer Switch"
                    ],
                    "name": "Ham Plug"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Triple Dimmer Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "12:4",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Din Switch"
                    ],
                    "name": "Suitcase DIN"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Din Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "12:5",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Din Switch"
                    ],
                    "name": "Isolation Transformer"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Din Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "12:6",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Din Switch"
                    ],
                    "name": "Din Lights"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Din Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "13:1",
                "type": "action.devices.types.SCENE",
                "traits": [
                    "action.devices.traits.Scene"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Environmental"
                    ],
                    "name": "Ham Environmental"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Environmental",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "14:1",
                "type": "action.devices.types.OUTLET",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Plug"
                    ],
                    "name": "Lobby Plug"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Plug",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "14:2",
                "type": "action.devices.types.OUTLET",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Plug"
                    ],
                    "name": "Ham Plug"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Plug",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "14:3",
                "type": "action.devices.types.OUTLET",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Plug"
                    ],
                    "name": "Lab Outlet"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Plug",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "14:5",
                "type": "action.devices.types.OUTLET",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Plug"
                    ],
                    "name": "Lobby Outlet"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Plug",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "2:0",
                "type": "action.devices.types.SCENE",
                "traits": [
                    "action.devices.traits.Scene"
                ],
                "name": {
                    "defaultNames": [
                        "Temperature HAM"
                    ],
                    "name": "Thermometer"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "Temperature HAM",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "2:1",
                "type": "action.devices.types.SCENE",
                "traits": [
                    "action.devices.traits.Scene"
                ],
                "name": {
                    "defaultNames": [
                        "Temperature HAM"
                    ],
                    "name": "Environmental Sensor"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "Temperature HAM",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "2:2",
                "type": "action.devices.types.SCENE",
                "traits": [
                    "action.devices.traits.Scene"
                ],
                "name": {
                    "defaultNames": [
                        "Temperature HAM"
                    ],
                    "name": "Environmental Sensor 2"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "Temperature HAM",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "3:0",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "Heavy HAM"
                    ],
                    "name": "Waterheater"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "Heavy HAM",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "4:0",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Light Switch"
                    ],
                    "name": "Room Lights 1"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Light Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "4:1",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Light Switch"
                    ],
                    "name": "Room Lights 2"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Light Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "4:2",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Light Switch"
                    ],
                    "name": "Park Lights 1"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Light Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "4:3",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Light Switch"
                    ],
                    "name": "Park Lights 2"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Light Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "4:4",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Light Switch"
                    ],
                    "name": "Park Lights 3"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Light Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "4:5",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Light Switch"
                    ],
                    "name": "Park Lights 4"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Light Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "4:6",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Light Switch"
                    ],
                    "name": "Park Lights 5"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Light Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "5:0",
                "type": "action.devices.types.OUTLET",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Wall Plug"
                    ],
                    "name": "TV"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Wall Plug",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "6:0",
                "type": "action.devices.types.OUTLET",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Multi Plug"
                    ],
                    "name": "Multi plug"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Multi Plug",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "8:10",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Switch"
                    ],
                    "name": "Office light"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "8:12",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Switch"
                    ],
                    "name": "Ham Light Switch"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "8:14",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Switch"
                    ],
                    "name": "Plug Demo"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "8:15",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Switch"
                    ],
                    "name": "Ham Light Switch"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "8:16",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Switch"
                    ],
                    "name": "ESP12-e"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "8:17",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Switch"
                    ],
                    "name": "ESP12-f"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "8:18",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Switch"
                    ],
                    "name": "esp12-s"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "8:19",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Switch"
                    ],
                    "name": "v6"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "8:20",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Switch"
                    ],
                    "name": "Ham Plug"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "8:25",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Switch"
                    ],
                    "name": "Bathroom Light"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "8:26",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Switch"
                    ],
                    "name": "Door Light"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "8:5",
                "type": "action.devices.types.SWITCH",
                "traits": [
                    "action.devices.traits.OnOff"
                ],
                "name": {
                    "defaultNames": [
                        "HAM Switch"
                    ],
                    "name": "ESP12-e"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM Switch",
                    "hwVersion": "1.0"
                }
            },
            {
                "id": "9:0",
                "type": "action.devices.types.LIGHT",
                "traits": [
                    "action.devices.traits.OnOff",
                    "action.devices.traits.Brightness"
                ],
                "name": {
                    "defaultNames": [
                        "HAM LED controller"
                    ],
                    "name": "LED Lights"
                },
                "willReportState": false,
                "deviceInfo": {
                    "manufacturer": "HAM Systems",
                    "model": "HAM LED controller",
                    "hwVersion": "1.0"
                }
            }
        ]
    }
}
```

The devices get listed on the Home App like this

![screenshot_2017-07-26-13-25-20-643_com google android googlequicksearchbox](https://user-images.githubusercontent.com/1592100/28617446-0698b0ec-7209-11e7-8977-2e0213d32d1a.png)

![screenshot_2017-07-26-13-25-28-066_com google android googlequicksearchbox](https://user-images.githubusercontent.com/1592100/28617450-08ab0038-7209-11e7-8a77-8ef3e0b496ec.png)

**Comment by Fleker** [comment] 2017-07-26 20:26
What happens when you try to execute a command on one of your lights? You stated that you did not receive anything on your endpoint. How does the Assistant respond?

**Comment by ekchatzi** [comment] 2017-07-26 22:46
turn office light on :
Sorry, I can't help with that yet.
Here's what I found on the web

Similarly, for turn water heater on I get web search results

To be frank, I cannot get it to respond for other apps as well, for example Airbnb or Emberlight. It always returns web search results. Maybe it has something to do with location? Same thing on the simulator, all responses are "Sorry, this action is not available on simulation", tried both real (Greek) and US location

**Comment by Fleker** [comment] 2017-07-28 03:34
Your Google account
<https://myaccount.google.com/preferences?pli=1#localization> is based on a
Greek locale?

**Comment by ekchatzi** [comment] 2017-07-28 13:29
The account that owns the action project and the google home device was in English (US). For some reason it started working today and I was able to implement the Action!

Thanks for the guidance !

**Comment by Fleker** [comment] 2017-08-28 17:55
Closing. We'll update the docs to clarify the invocation.

**Closed by Fleker** 2017-08-28 17:55 UTC
