### ISSUE TITLE
Unable to get SYNC requests after adding my device and login to it. 

### ISSUE THREAD

**Issue by tecsined** [actions-on-google/actionssdk-smart-home-nodejs#49] opened 2017-10-20 19:47 UTC
After I add my device on testing and logged my application I get a progress dialog with "Linking your ... account".. then I got an error: "Couldn't update the settings. Check your connection".

I am using for my automatization a azure function published on https but I never get this request
```
{
  "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcf",
  "inputs": [{
    "intent": "action.devices.SYNC"
  }]
}

```
Or any request. My project Id is kevostaging-183317 is there a way to see logs or something that tell me why a sync request is not being send to my API end point

**Comment by Fleker** [comment] 2017-10-20 21:32
Is there an issue with your account linking implementation?

**Comment by Fleker** [comment] 2017-11-01 19:14
I'm going to mark this as a duplicate of #50

**Closed by Fleker** 2017-11-01 19:14 UTC
